export const EDITORS_INIT = 'EDITORS_INIT';
export const TURN_EDITING_MODE_ON = 'TURN_EDITING_MODE_ON';
export const TURN_EDITING_MODE_OFF = 'TURN_EDITING_MODE_OFF';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INIT = 'AUTH_INIT';

export const GET_SAVINGS_START = 'GET_SAVINGS_START';
export const GET_SAVINGS_SUCCESS = 'GET_SAVINGS_SUCCESS';
export const GET_SAVINGS_FAIL = 'GET_SAVINGS_FAIL';

export const OPEN_HINT = 'OPEN_HINT';
export const CLOSE_HINT = 'CLOSE_HINT';